// Mocks generated by Mockito 5.4.5 from annotations
// in guiademoteisgo/test/presentation/pages/home_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:guiademoteisgo/core/usecases/usecase.dart' as _i6;
import 'package:guiademoteisgo/domain/entities/motel.dart' as _i5;
import 'package:guiademoteisgo/domain/repositories/motel_repository.dart'
    as _i2;
import 'package:guiademoteisgo/domain/usecases/get_moteis.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMotelRepository_0 extends _i1.SmartFake
    implements _i2.MotelRepository {
  _FakeMotelRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetMoteis].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMoteis extends _i1.Mock implements _i3.GetMoteis {
  MockGetMoteis() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MotelRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMotelRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.MotelRepository);

  @override
  _i4.Future<List<_i5.Motel>> call(_i6.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<List<_i5.Motel>>.value(<_i5.Motel>[]),
          )
          as _i4.Future<List<_i5.Motel>>);
}
